name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/contracts
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.16.1'
          cache: 'npm'
          cache-dependency-path: ./packages/contracts/package-lock.json
      - name: Install packages
        run: npm ci
      - name: Compile code
        run: npx hardhat compile
      - name: Run tests
        run: npx hardhat test

  frontend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/frontend
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build
        with:
          WORK_DIR: "${{env.working-directory}}"
